file_type: config_system

# inputs type options: {'BLE_input', 'analog_input', 'digital_input'}
# transform type options: {'linear'}
inputs:
  - name: 'leg_pressure_sensor' # string (required)
    id: 1
    type: 'BLE_input' # string (required)
    function:
      name: 'sensor_1_func' # string (required)
      parameters:
        speed: 100
        param2: 500
        param3: 20

outputs:
  - name: 'finger1_dc' # string (required)
    type: 'DC_motor' # string (required)
    pins:
      - type: 'in1_pin' # string (required)
        pin_number: 19 # int (required)
      - type: 'in2_pin' # string (required)
        pin_number: 21 # int (required)
      - type: 'sense_pin' # string (required)
        pin_number: 34 # int (required)
    safety_threshold: 20

  - name: 'finger2_dc' # string (required)
    type: 'DC_motor' # string (required)
    pins:
      - type: 'in1_pin' # string (required)
        pin_number: 23 # int (required)
      - type: 'in2_pin' # string (required)
        pin_number: 22 # int (required)
      - type: 'sense_pin' # string (required)
        pin_number: 35 # int (required)
    safety_threshold: 20
